In [1]:
import cv2 as cv
import numpy as np
image_path = "iris-gray.png"
img = cv.imread(image_path, cv.IMREAD_GRAYSCALE)

In [4]:
def horizontal_occurance(image):
    quantized = (image // 32).astype(np.uint8)
    occurance_matrix = np.zeros((8, 8), dtype=np.int32)
    rows, cols = image.shape
    
    for y in range(rows):
        for x in range(cols - 1):
            i = quantized[y, x]
            j = quantized[y, x + 1]
            occurance_matrix[i, j] += 1
    occurance_matrix = occurance_matrix + occurance_matrix.T
    return occurance_matrix
def vertical_occurance(image):
    quantized = (image // 32).astype(np.uint8)
    occurance_matrix = np.zeros((8, 8), dtype=np.int32)
    rows, cols = image.shape
    
    for y in range(rows - 1):
        for x in range(cols):
            i = quantized[y, x]
            j = quantized[y + 1, x]
            occurance_matrix[i, j] += 1
    occurance_matrix = occurance_matrix + occurance_matrix.T
    return occurance_matrix

In [5]:
print("Horizontal Co-occurance Matrix:")
print(horizontal_occurance(img))
print("Vertical Co-occurance Matrix:")
print(vertical_occurance(img))

Horizontal Co-occurance Matrix:
[[  362   159    14     3     0     0     0     0]
 [  159 40302  2924   204    56    21     4     0]
 [   14  2924 34788  2379   308    81    31     1]
 [    3   204  2379 11964  2320   328    87     6]
 [    0    56   308  2320  8546  1645   234    19]
 [    0    21    81   328  1645  5488  1093    52]
 [    0     4    31    87   234  1093  3362   370]
 [    0     0     1     6    19    52   370  1070]]
Vertical Co-occurance Matrix:
[[  404   102     9     2     3     0     0     0]
 [  102 41134  2341   106    52    65     5     0]
 [    9  2341 35570  2013   271   187    67     1]
 [    2   106  2013 12434  2115   397   147    13]
 [    3    52   271  2115  8694  1627   325    47]
 [    0    65   187   397  1627  5192  1089   154]
 [    0     5    67   147   325  1089  3068   485]
 [    0     0     1    13    47   154   485   818]]
